params: {
    #Width in pixels
    Width: "1600",
    
    #Height in pixels
    Height: "1200",
     
    # publish, buffer
    FrameHandler: "publish",

    # Off, Once, Continuous
    BalanceWhiteAuto: "Continuous",

    # Off, Daylight5000K, Daylight6500K, Tungsten2800K
    LightSourcePreset: "Tungsten2800K",
    
    # Mono8, Mono10, Mono10p, Mono12, Mono12p,
    # BayerGR8, BayerRG8, BayerGB8, BayerBG8, BayerGR10,
    # BayerGR10p, BayerRG10, BayerRG10p, BayerGB10, 
    # BayerGB10p, BayerBG10, BayerBG10p, BayerGR12, 
    # BayerGR12p, BayerRG12, BayerRG12p, BayerGB12, 
    # BayerGB12p, BayerBG12, BayerBG12p, RGB8, BGR8, 
    # YCbCr422_8 
    PixelFormat: "RGB8",
}
